apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-2
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 3000

  containers:
  - name: first-c
    image: kubegoldenguide/alpine-spin:1.0.0
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
  - name: second-c
    image: kubegoldenguide/alpine-spin:1.0.0
    securityContext:
      runAsUser: 2000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
