apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: pod-a
  name: pod-a
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pod-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pod-a
    spec:
      containers:
      - image: kubegoldenguide/simple-http-server
        name: pod-a
        resources: {}
status: {}
