apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: test5
  name: test5
spec:
  replicas: 1
  selector:
    matchLabels:
      run: test5
  strategy: {}
  template:
    metadata:
      labels:
        run: test5
    spec:
      containers:
      - image: kubegoldenguide/question-thirteen
        name: test5
        ports:
        - containerPort: 8000
       
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10        
