apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup : 3000
    fsGroup: 2000
  containers:
  - name: myapp
    image: busybox
    command: ["sh","-c", "sleep 1h"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false