apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    command: ["/bin/sh","-c", "ls /etc/config"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - configMapRef:
            name: configmap-test
    env:
      - name: SPECIAL1
        valueFrom:
            configMapKeyRef:
              name: configmap-test
              key: APPROLE
      - name: SPECIAL2
        valueFrom:
          configMapKeyRef:
              name: configmap-test
              key: APPID
    ports:
      - containerPort: 8080