apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    command: ["/bin/sh","-c", "ls -l /etc/config"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
    securityContext:
      runAsUser:  1000
  volumes:
    - name: config-volume
      configMap:
        name: configmap-test
  restartPolicy: Never